'use client'
import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Loader2, LockKeyhole } from 'lucide-react'
import { clearCart, setCartDeliveryMethod, useCartStore } from '@/lib/cart-store'
import { CheckoutSteps, type CheckoutStepId } from '@/components/checkout/CheckoutSteps'
import { AddressSelector } from '@/components/checkout/AddressSelector'
import { DeliveryOptions } from '@/components/checkout/DeliveryOptions'
import { PaymentMethods } from '@/components/checkout/PaymentMethods'
import { OrderReview } from '@/components/checkout/OrderReview'
import { OrderConfirmation } from '@/components/checkout/OrderConfirmation'
import { LoadingSkeleton } from '@/components/shared/LoadingSkeleton'
import type { Address, CheckoutGroup, CheckoutOrder, DeliveryMethod, OrderSummary, PaymentChoice } from '@/lib/types'
import Header from '@/components/Header'

const STEPS=[{id:'address',label:'العنوان'},{id:'delivery',label:'الشحن'},{id:'payment',label:'الدفع'},{id:'review',label:'المراجعة'}] as {id:CheckoutStepId;label:string}[]
function supports(product:string,method:DeliveryMethod){return product===method||(product==='both'&&method!=='platform_delivery')}
function defaultMethod(items:CheckoutGroup['items']):DeliveryMethod|null{return (['pickup','seller_delivery','platform_delivery'] as DeliveryMethod[]).find((m)=>items.every(i=>supports(i.product.deliveryMethod,m)))||null}

export default function CheckoutPage(){
 const cart=useCartStore();const [auth,setAuth]=useState<'loading'|'authenticated'|'anonymous'>('loading');const [step,setStep]=useState<CheckoutStepId>('address');const [address,setAddress]=useState<Address|null>(null);const [payment,setPayment]=useState<PaymentChoice>('online');const [notes,setNotes]=useState('');const [loading,setLoading]=useState(false);const [orders,setOrders]=useState<CheckoutOrder[]>([]);const [error,setError]=useState<string|null>(null)
 useEffect(()=>{let active=true;void fetch('/api/profile',{cache:'no-store'}).then(r=>{if(active)setAuth(r.ok?'authenticated':'anonymous')}).catch(()=>{if(active)setAuth('anonymous')});return()=>{active=false}},[])
 const groups=useMemo<CheckoutGroup[]>(()=>{const map=new Map<string,CheckoutGroup>();for(const item of cart.items){const id=item.product.sellerId;const old=map.get(id);if(old)old.items.push(item);else map.set(id,{sellerId:id,sellerName:item.product.sellerName,items:[item],deliveryMethod:cart.deliverySelections[id]||null})}return Array.from(map.values()).map(g=>{const selected=g.deliveryMethod&&g.items.every(i=>supports(i.product.deliveryMethod,g.deliveryMethod as DeliveryMethod))?g.deliveryMethod:null;const method=selected||defaultMethod(g.items);if(method!==g.deliveryMethod)setCartDeliveryMethod(g.sellerId,method);return {...g,deliveryMethod:method}})},[cart.items,cart.deliverySelections])
 const summary=useMemo<OrderSummary>(()=>{const subtotal=cart.items.reduce((n,i)=>n+i.product.price*i.quantity,0);return {subtotal,shipping:0,platformFee:0,discount:0,tax:0,total:subtotal}},[cart.items])
 const canDeliver=groups.length>0&&groups.every(g=>Boolean(g.deliveryMethod));const needsAddress=groups.some(g=>g.deliveryMethod&&g.deliveryMethod!=='pickup')
 function next(){setError(null);const ids:CheckoutStepId[]=['address','delivery','payment','review'];const i=ids.indexOf(step);if(step==='address'&&needsAddress&&!address){setError('اختر عنوان الاستلام قبل المتابعة.');return}if(step==='delivery'&&!canDeliver){setError('اختر طريقة استلام متاحة لكل بائع.');return}if(step==='payment'&&payment!=='online'){setError('طريقة الدفع المحددة غير مفعّلة حاليًا.');return}if(i<ids.length-1)setStep(ids[i+1])}
 function prev(){const ids:CheckoutStepId[]=['address','delivery','payment','review'];const i=ids.indexOf(step);if(i>0)setStep(ids[i-1])}
 async function place(){if(!cart.hydrated||!cart.items.length||loading)return;if(!canDeliver||(needsAddress&&!address)){setError('راجع طريقة الاستلام والعنوان قبل التأكيد.');return}setLoading(true);setError(null);try{const key=globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);const body={idempotencyKey:key,groups:groups.map(g=>({sellerId:g.sellerId,deliveryMethod:g.deliveryMethod,deliveryAddress:g.deliveryMethod==='pickup'?{}:{fullName:address?.fullName||'',phone:address?.phone||'',addressLine1:address?.street||'',district:address?.district||'',city:address?.city||'',governorate:address?.governorate||''},notes,items:g.items.map(i=>({productId:i.product.id,quantity:i.quantity}))}))};const r=await fetch('/api/orders/cart',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify(body)});const data=(await r.json()) as{orders?:CheckoutOrder[];existing?:boolean;error?:string};if(!r.ok||!data.orders?.length)throw new Error(data.error||'تعذر إنشاء طلبات السلة.');setOrders(data.orders);clearCart();setStep('review')}catch(e){setError(e instanceof Error?e.message:'تعذر إنشاء طلبات السلة.')}finally{setLoading(false)}}
 if(!cart.hydrated||auth==='loading')return <><Header/><LoadingSkeleton type="checkout"/></>
 if(auth==='anonymous')return <><Header/><main className="deba-checkout-v2-page" dir="rtl"><section className="deba-checkout-auth-card"><LockKeyhole size={28}/><span>DEBA CHECKOUT</span><h1>سجّل الدخول لإتمام الشراء</h1><p>سلتك محفوظة على هذا الجهاز، وسنربط الطلبات بحسابك بعد تسجيل الدخول.</p><Link href="/login?next=%2Fcheckout" className="deba-cart-primary-action">تسجيل الدخول</Link><Link href="/cart" className="deba-cart-secondary-action">العودة للسلة</Link></section></main></>
 if(cart.items.length===0&&orders.length===0)return <><Header/><main className="deba-checkout-v2-page" dir="rtl"><section className="deba-checkout-auth-card"><span>DEBA CHECKOUT</span><h1>لا توجد منتجات للشراء</h1><p>عد إلى السلة وأضف المنتجات التي تريد شرائها.</p><Link href="/cart" className="deba-cart-primary-action">فتح السلة</Link></section></main></>
 return <><Header cartCount={0}/><main className="deba-checkout-v2-page" dir="rtl"><header className="deba-checkout-v2-hero"><div><span>DEBA CHECKOUT</span><h1>إتمام الطلب</h1><p>راجع منتجاتك، اختر الاستلام والدفع، ثم أنشئ طلبًا آمنًا لكل بائع.</p></div><Link href="/cart" className="deba-cart-secondary-action"><ArrowRight size={16}/>العودة للسلة</Link></header>{orders.length===0?<><CheckoutSteps steps={STEPS} currentStep={step}/><div className="deba-checkout-v2-layout"><section className="deba-checkout-v2-main">{step==='address'?<AddressSelector selectedAddress={address} onSelect={setAddress}/>:null}{step==='delivery'?<DeliveryOptions groups={groups} selections={Object.fromEntries(groups.map(g=>[g.sellerId,g.deliveryMethod]))} onChange={(id,m)=>setCartDeliveryMethod(id,m)}/>:null}{step==='payment'?<PaymentMethods value={payment} onChange={setPayment}/>:null}{step==='review'?<OrderReview groups={groups} address={address} paymentMethod={payment} summary={summary} notes={notes} onNotesChange={setNotes}/>:null}{error?<div className="deba-checkout-error" role="alert"><LockKeyhole size={17}/><span>{error}</span></div>:null}<div className="deba-checkout-v2-actions">{step!=='address'?<button type="button" className="deba-cart-secondary-action" onClick={prev} disabled={loading}>السابق</button>:<span/>}{step!=='review'?<button type="button" className="deba-cart-primary-action" onClick={next}>التالي<ArrowRight size={16}/></button>:<button type="button" className="deba-cart-primary-action" onClick={()=>void place()} disabled={loading}>{loading?<Loader2 size={17} className="deba-spin"/>:null}{loading?'جارٍ إنشاء الطلبات...':'تأكيد الطلبات'}</button>}</div></section><aside className="deba-checkout-v2-sidebar"><div className="deba-checkout-sidebar-card"><span>ORDER SUMMARY</span><h2>ملخص الطلب</h2>{cart.items.map(i=><div key={i.id} className="deba-checkout-sidebar-item"><span>{i.product.title}</span><strong>{i.quantity} × {i.product.price.toLocaleString('ar-EG')} {i.product.currency}</strong></div>)}<div className="deba-checkout-sidebar-total"><span>الإجمالي</span><strong>{summary.total.toLocaleString('ar-EG')} ج.م</strong></div><small>الشحن والرسوم والضرائب لا تُحتسب قبل تفعيل محركاتها الفعلية.</small></div></aside></div></>:<OrderConfirmation orders={orders}/>}</main></>
}