'use client'
import { useEffect, useState, type FormEvent } from 'react'
import { CheckCircle2, Home, Loader2, MapPin, Plus, Save, X } from 'lucide-react'
import type { Address } from '@/lib/types'

type ProfilePayload = { profile?: { displayName?: string | null; city?: string | null; governorate?: string | null }; privateProfile?: { phone?: string | null; addressLine1?: string | null; addressLine2?: string | null; district?: string | null; postalCode?: string | null } }
function mapAddress(data: ProfilePayload): Address | null {
  const p = data.profile; const x = data.privateProfile; if (!p || !x) return null
  const street = x.addressLine1 || ''; const phone = x.phone || ''; const city = p.city || ''; const governorate = p.governorate || ''
  if (!street && !phone && !city && !governorate) return null
  return { id:'profile-default-address', label:'العنوان المحفوظ', fullName:p.displayName || 'صاحب الحساب', phone, governorate, city, district:x.district || '', street, building:'', floor:'', apartment:'', isDefault:true }
}

export function AddressSelector({ selectedAddress, onSelect }: { selectedAddress: Address | null; onSelect: (address: Address) => void }) {
  const [saved, setSaved] = useState<Address | null>(null), [loading, setLoading] = useState(true), [editing, setEditing] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState<string | null>(null), [message, setMessage] = useState<string | null>(null)
  const [form, setForm] = useState({ fullName:'', phone:'', governorate:'', city:'', district:'', street:'' })
  useEffect(() => { let active=true; void fetch('/api/profile',{cache:'no-store'}).then(async r => { const data=(await r.json()) as ProfilePayload & {error?:string}; if(!r.ok) throw new Error(data.error || 'تعذر تحميل العنوان.'); const address=mapAddress(data); if(!active)return; setSaved(address); if(address) { onSelect(address); setForm({fullName:address.fullName,phone:address.phone,governorate:address.governorate,city:address.city,district:address.district,street:address.street}) } }).catch(e=>{if(active)setError(e instanceof Error?e.message:'تعذر تحميل العنوان.')}).finally(()=>{if(active)setLoading(false)}); return()=>{active=false} },[onSelect])
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(null); setMessage(null); try { const response=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({displayName:form.fullName,phone:form.phone,governorate:form.governorate,city:form.city,district:form.district,addressLine1:form.street,isPublic:true})}); const data=(await response.json()) as {error?:string}; if(!response.ok) throw new Error(data.error || 'تعذر حفظ العنوان.'); const next={id:'profile-default-address',label:'العنوان المحفوظ',fullName:form.fullName.trim(),phone:form.phone.trim(),governorate:form.governorate.trim(),city:form.city.trim(),district:form.district.trim(),street:form.street.trim(),isDefault:true}; setSaved(next); onSelect(next); setEditing(false); setMessage('تم حفظ عنوان الاستلام في حسابك.') } catch(e) { setError(e instanceof Error?e.message:'تعذر حفظ العنوان.') } finally {setSaving(false)} }
  return <section className="deba-checkout-section-card"><div className="deba-checkout-section-head"><div><span>ADDRESS</span><h2>عنوان الاستلام</h2><p>يُستخدم العنوان المحفوظ في حسابك، ويمكن تحديثه قبل تأكيد الطلب.</p></div><MapPin size={22}/></div>
    {loading ? <div className="deba-checkout-inline-state"><Loader2 size={17} className="deba-spin"/>جارٍ تحميل بيانات العنوان...</div> : editing ? <form className="deba-checkout-address-form" onSubmit={save}><div className="deba-checkout-grid">{[['fullName','الاسم الكامل'],['phone','رقم الهاتف'],['governorate','المحافظة'],['city','المدينة'],['district','الحي / المنطقة'],['street','العنوان التفصيلي']].map(([key,label],i)=><label key={key} className={key==='street'?'is-wide':''}><span>{label}</span><input required={!['district'].includes(key)} value={form[key as keyof typeof form]} onChange={e=>setForm(cur=>({...cur,[key]:e.target.value}))} maxLength={key==='street'?180:120}/></label>)}</div>{error?<div className="deba-checkout-error" role="alert"><X size={17}/>{error}</div>:null}<div className="deba-checkout-form-actions"><button type="button" className="deba-cart-secondary-action" onClick={()=>setEditing(false)}>إلغاء</button><button type="submit" className="deba-cart-primary-action" disabled={saving}>{saving?<Loader2 size={17} className="deba-spin"/>:<Save size={17}/>}حفظ العنوان</button></div></form> : <div>{saved ? <button type="button" className={'deba-checkout-address-card'+(selectedAddress?.id===saved.id?' is-selected':'')} onClick={()=>onSelect(saved)}><span className="deba-checkout-address-icon"><Home size={18}/></span><span><strong>{saved.label}</strong><small>{saved.fullName} • {saved.phone}</small><small>{[saved.street,saved.district,saved.city,saved.governorate].filter(Boolean).join('، ')}</small></span>{selectedAddress?.id===saved.id?<CheckCircle2 size={19}/>:null}</button> : <div className="deba-checkout-empty-address"><MapPin size={18}/><div><strong>لا يوجد عنوان محفوظ بعد</strong><span>أضف عنوان الاستلام حتى نتمكن من إنشاء طلبات التوصيل.</span></div></div>}<button type="button" className="deba-checkout-add-address" onClick={()=>setEditing(true)}><Plus size={16}/>{saved?'تعديل العنوان المحفوظ':'إضافة عنوان جديد'}</button>{message?<p className="deba-checkout-success-message">{message}</p>:null}{error?<div className="deba-checkout-error" role="alert"><X size={17}/>{error}</div>:null}</div>}
  </section>
}