-- Reference codes must be generated by the database for every order insert.
alter table public.orders
  alter column reference_code
  set default ('DB-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,12)));

update public.orders
set reference_code = 'DB-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,12))
where reference_code is null;
