-- DEBA PHASE 2 / STEP 3
-- Seller dashboard, listing lifecycle, and private product-view telemetry.

begin;

alter table public.products
  drop constraint if exists products_status_check;

alter table public.products
  add constraint products_status_check
  check (
    status = any (
      array[
        'draft'::text,
        'published'::text,
        'paused'::text,
        'reserved'::text,
        'sold'::text,
        'donated'::text,
        'archived'::text
      ]
    )
  );

create table if not exists public.product_views (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  viewer_id uuid null references auth.users(id) on delete set null,
  visitor_key text not null,
  viewed_at timestamptz not null default now()
);

alter table public.product_views enable row level security;

revoke all on public.product_views from anon, authenticated;
grant all on public.product_views to service_role;

create index if not exists product_views_product_viewed_idx
  on public.product_views (product_id, viewed_at desc);

create index if not exists product_views_visitor_product_idx
  on public.product_views (visitor_key, product_id, viewed_at desc);

create or replace function private.record_product_view(
  p_product_id uuid,
  p_visitor_key text
)
returns boolean
language plpgsql
stable
security definer
set search_path = public, pg_catalog
as $function$
declare
  v_viewer_id uuid := auth.uid();
begin
  if p_product_id is null then
    return false;
  end if;

  if p_visitor_key is null
     or length(p_visitor_key) < 16
     or length(p_visitor_key) > 128
  then
    raise exception 'Invalid product visitor key';
  end if;

  if not exists (
    select 1
    from public.products p
    where p.id = p_product_id
      and p.status = 'published'
      and p.moderation_status = 'approved'
      and p.listing_type = 'sale'
  ) then
    return false;
  end if;

  if exists (
    select 1
    from public.product_views pv
    where pv.product_id = p_product_id
      and pv.visitor_key = p_visitor_key
      and pv.viewed_at > now() - interval '30 minutes'
  ) then
    return false;
  end if;

  insert into public.product_views (
    product_id,
    viewer_id,
    visitor_key,
    viewed_at
  )
  values (
    p_product_id,
    v_viewer_id,
    p_visitor_key,
    now()
  );

  return true;
end;
$function$;

create or replace function public.record_product_view(
  p_product_id uuid,
  p_visitor_key text
)
returns boolean
language sql
stable
security invoker
set search_path = ''
as $function$
  select private.record_product_view(p_product_id, p_visitor_key);
$function$;

revoke execute on function public.record_product_view(uuid, text) from public;
grant execute on function public.record_product_view(uuid, text) to anon, authenticated;

create or replace function private.guard_seller_product_lifecycle()
returns trigger
language plpgsql
security definer
set search_path = public, private, pg_catalog
as $function$
begin
  if (select private.is_admin()) or current_user = 'service_role' then
    return new;
  end if;

  if auth.uid() is not null and old.owner_id = auth.uid() then
    if (
      new.owner_id is distinct from old.owner_id
      or new.status is distinct from old.status
      or new.moderation_status is distinct from old.moderation_status
    )
    and coalesce(current_setting('deba.lifecycle_override', true), '') <> '1' then
      raise exception 'SELLER_PRODUCT_LIFECYCLE_USE_RPC';
    end if;
  end if;

  return new;
end;
$function$;

drop trigger if exists trg_guard_seller_product_lifecycle on public.products;

create trigger trg_guard_seller_product_lifecycle
before update of owner_id, status, moderation_status
on public.products
for each row
execute function private.guard_seller_product_lifecycle();

drop policy if exists products_insert_seller on public.products;
create policy products_insert_seller
on public.products
for insert
to authenticated
with check (
  (select private.is_admin())
  or (
    owner_id = (select auth.uid())
    and exists (
      select 1
      from public.profiles p
      where p.id = (select auth.uid())
        and p.account_type = 'seller'
    )
    and status = 'draft'
    and moderation_status = 'pending'
  )
);

drop policy if exists products_delete_seller on public.products;
create policy products_delete_seller
on public.products
for delete
to authenticated
using (
  (select private.is_admin())
  or (
    owner_id = (select auth.uid())
    and exists (
      select 1
      from public.profiles p
      where p.id = (select auth.uid())
        and p.account_type = 'seller'
    )
    and status = 'draft'
    and moderation_status in ('pending', 'rejected', 'needs_changes')
    and not exists (
      select 1 from public.orders o where o.product_id = products.id
    )
    and not exists (
      select 1 from public.offers o where o.product_id = products.id
    )
  )
);

create or replace function private.get_seller_dashboard(
  p_seller_id uuid
)
returns table (
  id uuid,
  title text,
  slug text,
  price numeric,
  currency text,
  quantity integer,
  status text,
  moderation_status text,
  condition_grade text,
  created_at timestamptz,
  updated_at timestamptz,
  published_at timestamptz,
  sold_at timestamptz,
  image_storage_path text,
  views_count bigint,
  offers_count bigint,
  active_chats_count bigint
)
language plpgsql
stable
security definer
set search_path = public, pg_catalog
as $function$
begin
  if p_seller_id is null or p_seller_id <> auth.uid() then
    raise exception 'Authenticated seller is required' using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.profiles p
    where p.id = p_seller_id
      and p.account_type = 'seller'
  ) then
    raise exception 'Seller account is required' using errcode = '42501';
  end if;

  return query
  select
    p.id,
    p.title,
    p.slug,
    p.price,
    p.currency,
    p.quantity,
    p.status,
    p.moderation_status,
    p.condition_grade,
    p.created_at,
    p.updated_at,
    p.published_at,
    p.sold_at,
    (
      select pi.storage_path
      from public.product_images pi
      where pi.product_id = p.id
      order by pi.is_primary desc, pi.sort_order asc
      limit 1
    ),
    (
      select count(*)
      from public.product_views pv
      where pv.product_id = p.id
    ),
    (
      select count(*)
      from public.offers o
      where o.product_id = p.id
    ),
    (
      select count(*)
      from public.chat_rooms cr
      where cr.product_id = p.id
        and cr.updated_at >= now() - interval '30 days'
    )
  from public.products p
  where p.owner_id = p_seller_id
  order by p.created_at desc
  limit 100;
end;
$function$;

create or replace function public.get_seller_dashboard()
returns table (
  id uuid,
  title text,
  slug text,
  price numeric,
  currency text,
  quantity integer,
  status text,
  moderation_status text,
  condition_grade text,
  created_at timestamptz,
  updated_at timestamptz,
  published_at timestamptz,
  sold_at timestamptz,
  image_storage_path text,
  views_count bigint,
  offers_count bigint,
  active_chats_count bigint
)
language sql
stable
security invoker
set search_path = ''
as $function$
  select * from private.get_seller_dashboard((select auth.uid()));
$function$;

revoke execute on function public.get_seller_dashboard() from public, anon;
grant execute on function public.get_seller_dashboard() to authenticated;

create or replace function private.update_seller_listing_status(
  p_product_id uuid,
  p_action text
)
returns public.products
language plpgsql
volatile
security definer
set search_path = public, private, pg_catalog
as $function$
declare
  v_uid uuid := auth.uid();
  v_product public.products%rowtype;
begin
  if v_uid is null then
    raise exception 'Authenticated seller is required' using errcode = '42501';
  end if;

  select p.* into v_product
  from public.products p
  where p.id = p_product_id
    and p.owner_id = v_uid
  for update;

  if not found then
    raise exception 'Listing not found or not owned by seller' using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.profiles p
    where p.id = v_uid
      and p.account_type = 'seller'
  ) then
    raise exception 'Seller account is required' using errcode = '42501';
  end if;

  set local deba.lifecycle_override = '1';

  case p_action
    when 'submit_for_review' then
      if v_product.status <> 'draft' then
        raise exception 'Only draft listings can be submitted for review';
      end if;
      if v_product.moderation_status not in ('pending', 'rejected', 'needs_changes') then
        raise exception 'Listing is not eligible for review submission';
      end if;
      update public.products
      set status = 'draft', moderation_status = 'pending', updated_at = now()
      where id = v_product.id;

    when 'pause' then
      if v_product.status <> 'published' or v_product.moderation_status <> 'approved' then
        raise exception 'Only approved published listings can be paused';
      end if;
      update public.products
      set status = 'paused', updated_at = now()
      where id = v_product.id;

    when 'resume' then
      if v_product.status <> 'paused' or v_product.moderation_status <> 'approved' then
        raise exception 'Only approved paused listings can be resumed';
      end if;
      update public.products
      set status = 'published', published_at = coalesce(published_at, now()), updated_at = now()
      where id = v_product.id;

    when 'mark_sold' then
      if v_product.status not in ('published', 'paused') then
        raise exception 'Only published or paused listings can be marked sold';
      end if;
      update public.products
      set status = 'sold', sold_at = coalesce(sold_at, now()), updated_at = now()
      where id = v_product.id;

    when 'archive' then
      if v_product.status not in ('draft', 'paused', 'sold') then
        raise exception 'Only draft, paused, or sold listings can be archived';
      end if;
      update public.products
      set status = 'archived', updated_at = now()
      where id = v_product.id;

    when 'restore' then
      if v_product.status <> 'archived' then
        raise exception 'Only archived listings can be restored';
      end if;
      update public.products
      set status = 'draft', moderation_status = 'pending', sold_at = null, updated_at = now()
      where id = v_product.id;

    else
      raise exception 'Unknown seller listing action';
  end case;

  select p.* into v_product
  from public.products p
  where p.id = v_product.id;

  return v_product;
end;
$function$;

create or replace function public.update_seller_listing_status(
  p_product_id uuid,
  p_action text
)
returns public.products
language sql
volatile
security invoker
set search_path = ''
as $function$
  select private.update_seller_listing_status(p_product_id, p_action);
$function$;

revoke execute on function public.update_seller_listing_status(uuid, text) from public, anon;
grant execute on function public.update_seller_listing_status(uuid, text) to authenticated;

create or replace function private.update_seller_listing(
  p_product_id uuid,
  p_title text,
  p_description text,
  p_price numeric,
  p_quantity integer,
  p_city text,
  p_governorate text,
  p_district text
)
returns public.products
language plpgsql
volatile
security definer
set search_path = public, private, pg_catalog
as $function$
declare
  v_uid uuid := auth.uid();
  v_product public.products%rowtype;
begin
  if v_uid is null then
    raise exception 'Authenticated seller is required' using errcode = '42501';
  end if;

  select p.* into v_product
  from public.products p
  where p.id = p_product_id
    and p.owner_id = v_uid
  for update;

  if not found then
    raise exception 'Listing not found or not owned by seller' using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.profiles p
    where p.id = v_uid
      and p.account_type = 'seller'
  ) then
    raise exception 'Seller account is required' using errcode = '42501';
  end if;

  if v_product.status in ('sold', 'archived') then
    raise exception 'Sold or archived listings must be restored before editing';
  end if;

  if p_title is null or length(btrim(p_title)) < 10 or length(btrim(p_title)) > 120 then
    raise exception 'Listing title must contain between 10 and 120 characters';
  end if;

  if p_price is null or p_price <= 0 then
    raise exception 'Listing price must be greater than zero';
  end if;

  if p_quantity is null or p_quantity < 0 then
    raise exception 'Listing quantity cannot be negative';
  end if;

  set local deba.lifecycle_override = '1';

  update public.products
  set
    title = btrim(p_title),
    description = nullif(btrim(coalesce(p_description, '')), ''),
    price = p_price,
    quantity = p_quantity,
    city = nullif(btrim(coalesce(p_city, '')), ''),
    governorate = nullif(btrim(coalesce(p_governorate, '')), ''),
    district = nullif(btrim(coalesce(p_district, '')), ''),
    updated_at = now(),
    status = 'draft',
    moderation_status = 'pending'
  where id = v_product.id;

  select p.* into v_product
  from public.products p
  where p.id = v_product.id;

  return v_product;
end;
$function$;

create or replace function public.update_seller_listing(
  p_product_id uuid,
  p_title text,
  p_description text,
  p_price numeric,
  p_quantity integer,
  p_city text,
  p_governorate text,
  p_district text
)
returns public.products
language sql
volatile
security invoker
set search_path = ''
as $function$
  select private.update_seller_listing(
    p_product_id,
    p_title,
    p_description,
    p_price,
    p_quantity,
    p_city,
    p_governorate,
    p_district
  );
$function$;

revoke execute on function public.update_seller_listing(uuid, text, text, numeric, integer, text, text, text) from public, anon;
grant execute on function public.update_seller_listing(uuid, text, text, numeric, integer, text, text, text) to authenticated;

create or replace function private.delete_seller_listing(
  p_product_id uuid
)
returns boolean
language plpgsql
volatile
security definer
set search_path = public, private, pg_catalog
as $function$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'Authenticated seller is required' using errcode = '42501';
  end if;

  if not exists (
    select 1 from public.profiles p
    where p.id = v_uid and p.account_type = 'seller'
  ) then
    raise exception 'Seller account is required' using errcode = '42501';
  end if;

  delete from public.products p
  where p.id = p_product_id
    and p.owner_id = v_uid
    and p.status = 'draft'
    and p.moderation_status in ('pending', 'rejected', 'needs_changes')
    and not exists (select 1 from public.orders o where o.product_id = p.id)
    and not exists (select 1 from public.offers o where o.product_id = p.id);

  return found;
end;
$function$;

create or replace function public.delete_seller_listing(
  p_product_id uuid
)
returns boolean
language sql
volatile
security invoker
set search_path = ''
as $function$
  select private.delete_seller_listing(p_product_id);
$function$;

revoke execute on function public.delete_seller_listing(uuid) from public, anon;
grant execute on function public.delete_seller_listing(uuid) to authenticated;

commit;